language: node_js
node_js:
  - "8.12.0"
  - "10.11.0"
  - "12.8.0"
  - "13.14.0"
  - "14.1.0"
  - "14.3.0"
script:
  - npm install --dev && npm test
notifications:
    slack: axiansiotnordic:nZLJBN5ZhPtsQYQS60SE92bA